services:
  atlasink:
    build:
      context: .
      dockerfile: Dockerfile
    image: atlasink:latest
    container_name: atlasink
    ports:
      - "${APP_PORT:-7200}:80"
    restart: unless-stopped
